# Generated by Django 2.0 on 2019-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171217_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPointTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(blank=True, default='Test String', max_length=100, null=True)),
                ('entrydate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
